Feature
qsharp-community/qram pull request #12
Opened 2020-06-24 16:29 UTC by shikharsingh3

Need to fix the error in src folder.

2020-06-24 17:16 UTC, crazy4pi314 commented
A couple of things b4 I can review this:
- [ ] Please update the description of the PR to indicate what functionality you are adding.
- [ ] Update your branch to current master
- [ ] Comment/add API documentation to you code so we can follow what you are doing. Also remove code that is not being used. 
- [ ] Please adhere to the [Q# style guide](https://docs.microsoft.com/en-us/quantum/resources/contributing/style-guide?tabs=guidance) for code formatting

2020-06-24 17:21 UTC, glassnotes commented
To add to @crazy4pi314 's comment, there are some general guidelines for submitting a PR [here](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/). There are also [contribution guidelines](https://github.com/qsharp-community/qram/blob/master/CONTRIBUTING.md) in the repo.

2020-06-29 18:40 UTC, crazy4pi314 requested changes

2020-06-29 18:40 UTC, crazy4pi314 commented on .vscode/launch.json
> +{
These are personal editor configs that should not be pushed to repo.

2020-06-29 18:40 UTC, crazy4pi314 commented on .vscode/tasks.json
> +{
Same here, these are personal editor configs that should not be pushed to repo.

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> +        (ControlledOnInt(address, ApplyPauliFromBitString(PauliX, true, value,_)))
Needs to have space after comma before _

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> +  newtype BBQRAM = (
This type is missing the read and write named items that will be necessary for making this API consistent with the implicit QROMs. Also should be named QRAM as we want it to be interchangeable for the user once created.

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> +  function BBQRAMOracle(dataValues : ((Int, Bool)[])) : BBQRAM{
Extra set of parens
```suggestion
  function BBQRAMOracle(dataValues : (Int, Bool)[] ) : BBQRAM{   
```

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> +        //let bbqrams =Mapped(BB, addressx);
If its code you are not using, please remove it. You can always go back for it in version control.

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> +           // w/ LookupBB <- bbqrams
You need this line, as well as a readout default value assignment for the writing operation for the QRAM type.

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> +  //  }
Not using, delete.

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> + operation ApplyBBQRAM(addressRegister : LittleEndian, auxillaryRegister:Qubit[], memoryRegister:Qubit[], target : Qubit) : Unit is Adj + Ctl
Please try to be consistent with whitespace styling, and if the declaration line is too long you can break it up like this:

```suggestion
 operation ApplyBBQRAM(
     addressRegister : LittleEndian, 
     auxillaryRegister : Qubit[],
     memoryRegister:Qubit[],
     target : Qubit
 )
: Unit is Adj + Ctl
```

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> +  /// # Summary
I was not clear on that the operation below did as the documentation is not filled in. The name `ApplyBBQRAM` is not clear what it is applying to.

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> + ///
Please complete the documentation.

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> +       let addressRegister1 = Reversed(addressRegister!);
You do not need the Reversed here, it will only cause issues as everything else uses `LittleEndian`.

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> +    ///
Please complete the documentation.

2020-06-29 18:40 UTC, crazy4pi314 commented on src/Library.qs
> +       let addressRegister1 = Reversed(addressRegister!);
Think about how you are doing the iteration below and you will not need this.

2020-06-29 18:40 UTC, crazy4pi314 commented on tests/QRamTest.qs
For this whole file, I would suggest refactoring and ensuring that you have the use submit not "nice" number of data values (i.e. not 2, 4, 8, ...) These tests are ok, but also as discussed in our standup the sorting of the data is not necessary and tests should not be on all sorted data. You can see how I have been doing this with the tests on my branch: https://github.com/qsharp-community/qram/tree/crazy4pi314/quantumdevwme/tests

2020-06-29 18:40 UTC, crazy4pi314 commented on tests/QRamTest.qs
> +        let m1 = (1, false);
Sample data can be moved to helper function in this namespace and thus don't need duplicated.

2020-06-29 18:40 UTC, crazy4pi314 commented on tests/QRamTest.qs
> +        let queryAddress = 0;
This should be an argument to the test helper function, or something the test loops over and tests each of addresses for a single test.

2020-06-29 18:51 UTC, crazy4pi314 commented
> A couple of things b4 I can review this:
> 
> * [ ]  Please update the description of the PR to indicate what functionality you are adding.
> * [x]  Update your branch to current master
> * [ ]  Comment/add API documentation to you code so we can follow what you are doing. Also remove code that is not being used.
> * [ ]  Please adhere to the [Q# style guide](https://docs.microsoft.com/en-us/quantum/resources/contributing/style-guide?tabs=guidance) for code formatting

After a detailed review, three of the four items listed here still are not done, can you please address them? Thanks!

2020-07-06 21:22 UTC, closed without merging